server:
  port: 8888

spring:
  redis:
    database: 0
    host: 192.168.0.121
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0